# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty
# relative_permalinks: true

# Setup
title_part_one:            Journey into the
title_part_two:            Unknown 
tagline:          'A journey deep into the heart of the Unknown'
description: 	  ''
url:              http://vivekjuneja.github.io
baseurl: /
name: Vivek Juneja
email: vivekjuneja@gmail.com
email_full: mailto:vivekjuneja@gmail.com
website: https://cloudgeek.in
website_full: https://cloudgeek.in
github: trending
twitter: vivekjuneja
tel: +82
tel_full: tel:+82





author:
  name:           'Vivek Juneja'
  url:            https://twitter.com/vivekjuneja

paginate:         1 

# Custom vars
version:          0.0.1

github:
  repo:           https://github.com/vivekjuneja

gems: [jekyll-gist, jekyll-paginate, jekyll-last-modified-at]

google_analytics: UA-83374110-1

last_modified_at:	17-Dec-2016 
