# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
# relative_permalinks: true

# Setup
title:            Journey into the Unknown 
tagline:          'A journey deep into the heart of the Unknown'
description:      'I love technology, the mystery of human mind, Artificial Intelligence, behaviorial economics, design thinking and the chance to build things that people love. This is my account of the journey into my interests.'
url:              http://vivekjuneja.github.io
baseurl: /
name: Vivek Juneja
email: vivekjuneja@gmail.com
email_full: mailto:vivekjuneja@gmail.com
website: https://cloudgeek.in
website_full: https://cloudgeek.in
github: trending
twitter: vivekjuneja
tel: +82
tel_full: tel:+82





author:
  name:           'Vivek Juneja'
  url:            https://twitter.com/vivekjuneja

paginate:         1 

# Custom vars
version:          0.0.1

github:
  repo:           https://github.com/vivekjuneja

gems: [jekyll-gist, jekyll-paginate, jekyll-last-modified-at]
