# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
# relative_permalinks: true

# Setup
title:            Back to Basics 
tagline:          'Going deep into Technology'
description:      'A ride deep into the basics of Container, Orchestration, Cloud Platforms, DevOps, Microservices, Resilience Engineering and anything that makes distributed systems work'
url:              http://vivekjuneja.github.io
baseurl:          /

author:
  name:           'Vivek Juneja'
  url:            https://twitter.com/vivekjuneja

paginate:         1 

# Custom vars
version:          0.0.1

github:
  repo:           https://github.com/vivekjuneja

gems: [jekyll-gist, jekyll-paginate]
