# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
# relative_permalinks: true

# Setup
title:            Back to Basics 
tagline:          'Going deep into Technology'
description:      'A ride deep into the basics of Container, Orchestration, Cloud Platforms, DevOps, Microservices, Resilience Engineering and anything that makes distributed systems work'
url:              http://vivekjuneja.github.io
baseurl: /
name: Vivek Juneja
email: vivekjuneja@gmail.com
email_full: mailto:vivekjuneja@gmail.com
website: https://cloudgeek.in
website_full: https://cloudgeek.in
github: trending
twitter: vivekjuneja
tel: +82
tel_full: tel:+82





author:
  name:           'Vivek Juneja'
  url:            https://twitter.com/vivekjuneja

paginate:         1 

# Custom vars
version:          0.0.1

github:
  repo:           https://github.com/vivekjuneja

gems: [jekyll-gist, jekyll-paginate, jekyll-last-modified-at]
